GET http://localhost:3000/
###

GET http://localhost:3000/movies/ 
###

GET http://localhost:3000/movies/58/
###

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "directorId": 46,
    "movieName": "Avatar",
    "leadActor": "chin-chang"
}
###

PUT http://localhost:3000/movies/12/
Content-Type: application/json

{
    "directorId": 12,
    "movieName": "Pencil",
    "leadActor": "Prabhas"
}
###

DELETE http://localhost:3000/movies/12/

